### ISSUE TITLE
Response times

### ISSUE THREAD

**Issue by markusahlstrand** [noodlefrenzy/node-amqp10#138]
First of all, it's awesome that there finally is a amqp 1.0 library for node.js!

One of the reasons I was eager to try out amqp was that I hoped we would get better latency with amqp than with the Azure Sdk for node (using http). Currently I've been testing with the following setup which gives me a response time of about 100 ms which is a substantial improvement compared to the Azure Sdk even when using a keep-alive agent, but still not quite as fast as I was hoping for.

```
var AMQPClient = require('amqp10').Client;
var AMQPPolicy = require('amqp10').Policy;
var client = new AMQPClient(AMQPPolicy.merge({
  senderLinkPolicy: {
    callbackPolicy: AMQPPolicy.Utils.SenderCallbackPolicies.OnSent
  }
}, AMQPPolicy.ServiceBusTopic));
```

So, now to my questions: 
- It does seem that the benchmarks for using for example RabbitMQ with other sdk's they typically get response times less than 10 ms for small messages (judging from blogposts..). Is the relatively longer response time likely to be related to the use of Azure Servicebus or could there be some part of the library that could be tweaked from a performance standpoint?
- What guarantees do we get from the ServiceBus when the message is in the OnSent-state compared to the Settled state? Did we get some kind of ack from the server at this point or is it more "fire and forget"?

Thanks

**Comment by noodlefrenzy** [comment]
This is ServiceBus queues, right? I'm fairly certain a large chunk of that latency is related to that, I know Matt's run some numbers for other servers and had much better perf and I've run some against EventHub with faster timings. However, I'm also sure we have some slowness in our code (mostly due to my original authorship) - Matt's been doing his best to improve it, but he's obviously focused on qpidd since that's his primary case. If you had the time and the knowledge to make a pass through and look for any obvious issues, we appreciate all the help we can get :)

Callback OnSent means "call me back as soon as I send the message", so it is fire-and-forget. OnSettled waits for a disposition frame from ServiceBus letting us know the message has been settled on their end (which in theory only happens once it's been stored/replicated for durable delivery).

**Comment by markusahlstrand** [comment]
Thanks for the answer. Think I'll go digging a bit on the servicebus side to see if there's something not configured correctly.
I'd be happy to help out to the best of my ability, but the amqp stuff takes a while to wrap my head around.

**Comment by mbroadst** [comment]
I actually did some quick benchmarks the other day, and while we have lost a little performance up front (for small batches of messages), we have gained some considerable time in the higher numbers. Most of our performance issues (memory and cpu) revolve around a few issues:

  - we use BufferLists instead of directly using node's streams api (I don't see this changing any time soon unless you've got a lot of time on your hands :smile:)
  - AMQP 1.0 itself uses 64bit integers for the basis of all the things sent over the wire (descriptors, et al). This is probably reason number one why we will never reach the same speed scores as e.g. amqp.node or any of the other 0-9-1 implementations
  - Our decision to switch over to a primarily Promise-based api can certainly incur some performance hits over a straight callback-based api. But we feel that promises compose better, and allow for more readable/maintainable code, so the tradeoff is "worth it" here imho.
  - Finally, and least importantly, we have a number of cases in the codebase where EventEmitters are being used to signal events when we could really just be making direct function calls. I'm working on cleaning up most of this atm, so I'll run the benchmarks again when thats over

Here are the original benchmarks:
```
ACTIVEMQ+amqp10 (BASELINE):
=> sent 10 messages in 32ms
=> sent 100 messages in 216ms
=> sent 1000 messages in 2538ms
=> sent 10000 messages in 26144ms
=> sent 100000 messages in 127809ms

QPID+amqp10:
=> sent 10 messages in 32ms           (0.00x)
=> sent 100 messages in 100ms         (2.16x)
=> sent 1000 messages in 929ms        (2.73x)
=> sent 10000 messages in 6523ms      (4.00x)
=> sent 100000 messages in 37412ms    (3.41x)

RABBITMQ (1.0)+amqp10:
=> sent 10 messages in 17ms           (1.88x)
=> sent 100 messages in 54ms          (4.00x)
=> sent 1000 messages in 262ms        (9.68x)
=> sent 10000 messages in 1822ms      (14.35x)
=> sent 100000 messages in 26388ms    (4.84x)

RABBITMQ (0-9-1 with amqp.node):
=> sent 10 messages in 4ms            (8.00x)     VS QPID (8.00x)
=> sent 100 messages in 21ms          (10.28x)    VS QPID (4.76x)
=> sent 1000 messages in 146ms        (17.38x)    VS QPID (6.36x)
=> sent 10000 messages in 1409ms      (18.55x)    VS QPID (4.62x)
=> sent 100000 messages in 31331ms    (4.07x)     VS QPID (1.19x)
```

Here are the benchmarks for v2.0.0 I ran yesterday:
```
=> sent 10 messages in 49ms
=> sent 100 messages in 91ms
=> sent 1000 messages in 500ms
=> sent 10000 messages in 3491ms
=> sent 100000 messages in 30623ms
```

**Comment by mbroadst** [comment]
Additionally, I think the focus on 2.0.0 right now is to improve the overall usability of the library for a number of different AMQP 1.0 related use cases (like Mike said, I'm _not_ using this for Azure/ServiceBus/EventHub), and then to focus on performance again after all is said and done. As  you can, performance is increasing anyway during this process and hopefully that continues

**Comment by noodlefrenzy** [comment]
Woohoo, those perf numbers are great, Matt! Given that we haven't actually spent any time focused explicitly on perf, that's pretty awesome.

**Comment by mbroadst** [comment]
For reference, here's the code used for the benchmark (incredibly basic right now, I'm sure we can do much better given a little bit of effort :smile:):

```
'use strict';
var AMQPClient = require('./lib').Client;

var client = new AMQPClient(),
    messageCount = parseInt(process.argv[2]) || 10,
    receivedCount = 0,
    start, finish;

client.connect('amqp://localhost')
  .then(function() {
    return Promise.all([
      client.createReceiver('amq.topic'),
      client.createSender('amq.topic')
    ]);
  })
  .spread(function(receiver, sender) {
    receiver.on('message', function(message) {
      receivedCount++;
      if (receivedCount === messageCount) {
        finish = new Date();
        console.log('=> sent ' + messageCount + ' messages in ' + (finish.getTime() - start.getTime()) + 'ms');
        process.exit(0);
      }
    });

    var start = new Date();

    var promises = [];
    for (var i = 0; i < messageCount; i++)
      promises.push(sender.send('test'));
    return Promise.all(promises);
  });
```

**Comment by markusahlstrand** [comment]
As most of the cases it turns out that I've done something pretty stupid in the servicebus config.. I'll fix that and run the same benchmarks with with the servicebus. I'd be really happy if we reach response times in that range with Azure Servicebus.

Thanks

**Comment by markusahlstrand** [comment]
Ran the benchmark on Azure now with the following results:
```
=> sent 10 messages in 60 - 500 ms
=> sent 100 messages in 250 - 600 ms
=> sent 1000 messages in 1400 - 1700 ms
=> sent 10000 messages in 13000 - 16000 ms 
```

The response times differ quite a bit for each request and are by far not as good as for the results you got with rabbit, but certainly good enough for our use cases. Not sure how much difference it makes to run the mq locally on the machine compared to in the same data center as I did in my test. 

An interesting observation is that it took either exactly 16 och 32 ms to send a single message. Does this depend on in which state the connection is before the message is sent or is it likely to be something internal to Azure Servicebus.

**Comment by noodlefrenzy** [comment]
With all clients our team has used, we've seen high variance in Azure ServiceBus requests - not just Node. We've talked to the team and they have worked on mitigations to smooth that out, but it's not totally fixed. I think they might be moving it to a backend more similar to EventHub in the future to make it even more dependable w.r.t. latency, but that's just hearsay, don't quote me on it. :)

**Comment by markusahlstrand** [comment]
Still looking for a good enough excuse to play with EventHub, but so far ServiceBus seems cover our needs.

As mentioned the perf is sufficient for our needs so from my perspective we can close this issue.

**Comment by mbroadst** [comment]
@markusahlstrand thanks for the perf numbers. I'll try to spend some time in the next few weeks to put together an actual benchmark suite so we can keep track of these numbers as we refactor the codebase.
