### ISSUE TITLE
Event Hub Checkpoints

### ISSUE THREAD

**Issue by robblovell** [noodlefrenzy/node-amqp10#163]
Would like a feature to set Event Hub Checkpoints.  Currently, using a filter x-opt-offset doesn't seem to work as a poor man's checkpointing. There should be a way to tell the Event Hub to remember a checkpoint in the same way you can do this in the CSharp libraries.

**Comment by robblovell** [comment]
I have an email to some contacts inside Microsoft Azure, I am hoping that they will provide guidance.

**Comment by robblovell** [comment]
ServiceBusExplorer stores a checkpoint json file client side on exit that contains stuff like this:
```json
[
  {
    "namespace": "stagetcuservicebusmojious",
    "eventHub": "vehicleeventhub",
    "consumerGroup": "testharnessconsumergroup",
    "leases": {
      "2": {
        "PartitionId": "2",
        "Owner": "ServiceBusExplorer",
        "Token": null,
        "Epoch": 0,
        "Offset": "68721645648",
        "SequenceNumber": 115761
      },
      "3": {
        "PartitionId": "3",
        "Owner": "ServiceBusExplorer",
        "Token": null,
        "Epoch": 0,
        "Offset": "51542192344",
        "SequenceNumber": 90723
      }
   }
}
```

**Comment by noodlefrenzy** [comment]
We definitely won't add anything like that to this library, since it's an AMQP 1.0 library and not geared around Azure specifically, but my colleague and I did some earlier work to try and wrap this with logic to store EH offsets in Azure Table Storage - see https://github.com/jmspring/node-sbus and https://github.com/noodlefrenzy/node-sbus-amqp10.

Unfortunately, I've been so busy on other things I haven't had a chance to start upgrading node-sbus-amqp10 to use the new v2 API.

**Comment by robblovell** [comment]
I did see the node-sbus project, it makes sense to have the checkpoint functionality implemented there. I will look over there and poke around a bit.
