### ISSUE TITLE
How to handle asynchronous processing in receivers?

### ISSUE THREAD

**Issue by ianwsperber** [noodlefrenzy/node-amqp10#199]
I am using the library to process messages from event hub and would like to do some asynchronous work prior to handling the next message on a receiver. The only way I have found to do so is to set the filter options:

```
_.set(filterOptions, ['attach', 'receiverSettleMode'], amqp1.Constants.receiverSettleMode.settleOnDisposition)
 _.set(filterOptions, 'creditQuantum', 1)
```

and then in my receiver:

```
receiver.on('message', msg => {
   const self = this
   doAsyncStuff(msg, () => self.accept(msg))
})
```

Is this the best/only way of achieving my desired behavior?

**Comment by mbroadst** [comment]
@ianwsperber yep, that's how I do it, are you experiencing any issues?

**Comment by mbroadst** [comment]
@ianwsperber so flow control in AMQP 1.0 is based on link `credit` (described in the spec [here](http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#doc-flow-control), though that can be a little dense), and credit is adjusted based on `disposition` of messages. Credit for a receiver link is basically how many messages you want to permit the remote side to send down to you.

A ReceiverLink has two possible modes: settle on disposition, and auto settle (the default). Auto settle mode means that as messages are received they are automatically settled with a disposition (in this case of "accepted"). Settle on disposition means that it's up to the user of the library to settle these messages explicitly.  When message disposition is handled, flow control is also "pumped", and a `credit` function is called for that particular link (this is defined in the link policy). 

The `creditQuantum` is an amqp10 concept that is used as part of our credit functions in order to determine how many credits to add by default under certain conditions: https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/policy_utilities.js#L25.   I'm not exactly sure what your use case is, but you can also specify your own credit function and altogether forego the defaults/use of a credit quantum. 

It does occur to me upon writing this that our defaults can lead to a pretty "chatty" client, in that we send dispositions for each message. Disposition is possible for a batch of messages in a single message: https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/receiver_link.js#L51 (note that you can pass in an array of messages to settle all at the same time). 

Hope this helps, let me know if you need any more clarification I'm sure I've missed some information as it's a bit early over here! @noodlefrenzy may want to chime in as well.

**Comment by ianwsperber** [comment]
@mbroadst Thanks for the thorough explanation. My specific use case requires processing messages on a single event hub partition in order ("chronologically"). If I continue using settle on disposition but increase the credit quantum will I have a reasonable guarantee that I will be processing messages in order? And is there an "intelligent" way of choosing the right credit quantum value?

It would be nice if there was documentation in the README around this behavior. I had been looking for an equivalent to the behavior `node-amqp` library, where enabling manual acknowledgement of messages is as simple as passing in the options `{ack: true}`. Not much more complicated here, but it's sort of hidden in the tests. Happy to help if possible!

**Comment by mbroadst** [comment]
@ianwsperber Unfortunately I think that this is one of those things you'll need to fine-tune to your application if the defaults aren't working for you. You have an absolute guarantee that you will be processing messages in order, as you are inherently working with queues.  You might find that a sort of sliding window in your custom `credit` function gives you better performance, I think you'll just need to experiment further.

I agree about the documentation, unfortunately that's a piece of the puzzle that is often sidelined due to time constraints. Also, a comparison to node-amqp is muddied simply by the difference in protocols: AMQP 1.0 is a much more involved protocol than 0-9-1. Any help here would be much appreciated, and I'm sure we could walk you through any questionable sections!

**Comment by ianwsperber** [comment]
Ok, thanks again @mbroadst . If I have some time in the next week or so I'll create a PR drafting some additional documentation in the README (or elsewhere, if you have a better suggestion)

**Comment by ianwsperber** [comment]
Hi again @mbroadst - unfortunately it appears that setting a credit quantum greater than 1 is preventing me from processing messages in order when I need to do asynchronous work on each message (to return to my original problem). The below snippet fails:

```
let lastSequenceNumber
receiver.on('message', function (msg) {
  const self = this

  lastSequenceNumber = msg.annotations.value['x-opt-sequence-number']

  return setTimeout(() => {
    const lastSequenceNumber = msg.annotations.value['x-opt-sequence-number']
    if (lastSequenceNumber !== sequenceNumber) {
      throw new Error('Message processing not syncronous!')
    }

    self.accept(msg)
  }, Math.random() * 1000)
})
```

Any thoughts?

**Comment by mbroadst** [comment]
@ianwsperber incoming messages will be in order (just remember, fundamentally you are dequeuing from a FIFO queue). What can't be accounted for is how quickly you process the messages on the client side.  What seems to be happening in your snippet above is that you are setting a creditQuantum of greater than 1, and each time you receive a message incrementing the `lastSequenceNumber`, waiting a random number of seconds, and then comparing the received sequence number to the `lastSequenceNumber`.  This of course will result in values that are not equal because you are indeed receiving other messages in the meantime (most likely almost at the same time, but definitely in sequential order) which triggers the callback to continue to increment `lastSequenceNumber`.

You have basically two choices if you need to operate on messages sequentially: 
  * set the credit quantum to 1 (this shouldn't have such a performance impact as you've noted above, with qpid I have _much_ higher numbers, so you might want to speak to someone at microsoft about SB/EH)

  * set the credit quantum to some higher number that's tailored to your particular use case, and simply use the `receive` callback to push the messages onto a local queue that you process sequentially. Each time you process a message you can call `accept` on the original receiver, and this way you can receive e.g. batches of 100 messages at a time in sequential order.

hth

**Comment by ianwsperber** [comment]
The key point I needed clarification on is that messages will still arrive
in order in the receiver. I'll implement the local queue solution and
respond with my implementation, to give a reference for anyone else who
encounters this issue (I believe someone on my team attempted this
previously but caused a memory leak by constructing an enormous promise
chain, or something to that effect). I'll also open a support ticket with
Azure asking for clarification on the single creditQuantum performance
issue. Thanks again

**Comment by mbroadst** [comment]
@ianwsperber you might be interested in the support for streams I've recently added for v3, I'll push a semver minor release today if you're interested in using them. `AMQPClient` now has `createSenderStream`/`createReceiverStream`, so you can work with links as an ordered stream. Otherwise, closing this issue now as I believe your question has been resolved.
