### ISSUE TITLE
Stream support for receivers and senders

### ISSUE THREAD

**Issue by jacoscaz** [noodlefrenzy/node-amqp10#218]
It'd be nice to have senders and receivers either support streaming natively or be made easily trappable into streams. Discussing this on gitter with @mbroadst, seems like the main issue here is the absence of a fine-grained credit setting beside `addCredits()` to drop the credit amount to 0 when `Readable.prototype.push()` calls within `read()` return `false`. Will try manually resetting credits using `addCredits(0, {linkCredit: 0})` and see how that goes.

**Comment by mbroadst** [comment]
@jacoscaz let's start here, I have a prototype up for the readable receiver stream on [this branch](https://github.com/noodlefrenzy/node-amqp10/tree/readable-stream). There is a lot to be improved here:

  * it just wraps the `ReceiverLink`, we could probably improve performance if this inherited `ReceiverLink` instead and called `push` instead of emitting the message on message receipt

  * it is basically non-configurable, using the default highWatermark of 16 for credit

  * ??? - stuff I haven't thought of

I'd be very interested in hearing your use case requirements, I think this is a nice start but the user api could be greatly improved.

**Comment by mbroadst** [comment]
I've gone ahead and added an even more basic `SenderStream` (`WritableStream`), as well as an integration test piping the two together. We should track discussion of these all on this issue

**Comment by jacoscaz** [comment]
@mbroadst well, that was fast :).

I started working on an almost identical solution [here](https://github.com/jacoscaz/node-amqp10/commit/a2c381c0a23b22e53252e15e9bef226454cbd35a), although your code looks a lot better.  Didn't have time to get to a PR-worthy commit.

Wouldn't it be better to keep the interface to the messages (stream vs. event) separate from the link's policy? That's why I opted for a `createReceiveStream()` method in `amqp_client.js`.

**Comment by jacoscaz** [comment]
@mbroadst Done a bunch of testing and small edits in my branch and issued a PR with some ideas. Feel absolutely free to discard parts or all of it. Had switch to using `.then()` in `SenderStream.prototype._write()` as I noticed not using it was messing up message ordering in my tests using servicebus queues (see `test/integration/servicebus/queues/streams.test.js`).

**Comment by mbroadst** [comment]
@jacoscaz hey, thanks for the response here. Some thoughts:

   * I agree that your idea of `createSenderStream`/`createReceiverStream` lowers the maintenance burden, let's go with that.

   * I left code in the `SenderStream` to do sends both ways because in my testing the speed differential was sort of amazing. I think we should figure out how best to support both scenarios.. perhaps switching on sndSettleMode/the callback policy, or batching disposition for the sent messages? Need to look into this.

  * I think we could make the `ReceiverSream` similarly "smart" when it comes to message disposition, sending disposition for batches of messages after some sort of "debounced" timeout rather than auto-acking for every message (currently the default)

Do you have any other comments after using it? Or have you not yet had the chance to give it a real go :smile:

**Comment by mbroadst** [comment]
@jacoscaz also wrt the bit of code you used for decoding the JSON payload: if you are always assuming JSON data in `message.body` you can override your receiver link's `decoder`: https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/default_policy.js#L98.

**Comment by jacoscaz** [comment]
Hey @mbroadst.

- About JSON parsing, yes, my mistake. I removed that in a later commit.
- I like the idea of sending disposition for batches. Sounds good. 
- I've just made a dumb test - a sender process, a receiver process - and exchanged little less than 20k messages, 1 message sent every 10ms. When I abruptly stopped the test, the servicebus queue was left with 4 messages on it - zero build up, which is nice. 

I should be able to integrate receiver / sender streams within our system in the next 48 hours. Will update you as I go on.

**Comment by mbroadst** [comment]
@jacoscaz fantastic, I'll continue to update the branch here as I have a few hours free before I'm chained back down to reality

**Comment by mbroadst** [comment]
@jacoscaz I think we can close this?

**Comment by jacoscaz** [comment]
Absolutely, yes! Very happy with it. Thanks a bunch!

Native stream support (rather than going through the current event emitter) might be worth tracking in a separate issue, though.

**Comment by mbroadst** [comment]
@jacoscaz agreed, I'll open an issue for it

**Comment by mbroadst** [comment]
@jacoscaz hey, if you're still using this I just pushed a PR for a `SenderLink` feature I'm calling `noReply`. The idea here being that sends would no longer return a Promise (i.e. "track" the send) when `send` is called on them with `{ noReply: true }` set.  The performance increase is remarkable (something like 50x faster on the streams test which used to take `3979ms` vs `79ms` now).
