### ISSUE TITLE
Is there an automatic reconnection when a "detached" error occurs?

### ISSUE THREAD

**Issue by vIceBerg** [noodlefrenzy/node-amqp10#248]
HI!

Here`s my code:

```
connect1();
connect2();

function connect1() {
  myFirstSender  = null;
   connectToAzureTopic("myUrl", "myQueueName", connect1, "my first topic").then(function(sender) {
     myFirstSender = sender;
   });
}
function connect2() {
  mySecondSender = null;
   connectToAzureTopic("myUrl2", "myQueueName", connect2, "my second topic").then(function(sender) {
     mySecondSender = sender;
   });;
}
function connectToAzureTopic(topicUrl, queueName, reconnectFnc, ident) {
		var client_ = new AMQPClient(policy);
		return client_.connect(topicUrl).then(function () {
			return client_.createSender(queueName).then(function (sender) {
				sender.on('errorReceived', function (tx_err) {
					log(ident, queueName, '===> TX ERROR: ', tx_err);
				});
				sender.on('detached', function () {
					log("event detached", ident, arguments);
					client_.disconnect().then(function() {
						log("Waiting 1000ms before reconnecting");
						return q.delay(1000).then(reconnectFnc);
					});
				});
				return sender;
			}).error(function (e) {
				log(topicUrl, "connection error:", e);
			});
		});
	}
```

And I use myFirstSender and mySecondSender in code to send messages

So, when I receive a "detached" event, my code disconnect the client, wait 1 seconds and reconnect using the provided function (connect1 or connect2).

I thought it was a proper pattern.

But when I get a "detached" event,  after that I get TimeOut error every 10 minutes... So it makes me think that there's an open connection somewhere that does nothing...

So what's wrong with my code?

Thanks

**Comment by mbroadst** [comment]
first of all, the default behavior is to auto reconnect and restablish links on reconnect unless you specify otherwise in your policy - just so you're aware of that.

I'm not really sure about the 10min timeout errors, that sounds like maybe a setting specific to azure. You could potentially monitor the `_senderLinks` and `_receiverLinks` of your client's `_session`, in order to determine how many links have been created. It would definitely be helpful to get a debug log if it was possible for you to provide that? (running your script with `DEBUG=amqp*` as an environment variable).

**Comment by vIceBerg** [comment]
Hi!

So my reconnect code is not needed, isn't that right?

I'll enable the debug variable and get back to you.

**Comment by mbroadst** [comment]
@vIceBerg yep! if you check [this](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/policy.js#L39) you'll see the default settings for `reconnect`, which are used unless otherwise specified. Furthmore, we have sender and receiver link `reattach` settings [here](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/service_bus_policy.js#L19) and [here](https://github.com/noodlefrenzy/node-amqp10/blob/master/lib/policies/service_bus_policy.js#L42) specifically defined for ServiceBus/EventHub users

**Comment by mbroadst** [comment]
@vIceBerg are you still having an issue here?

**Comment by vIceBerg** [comment]
Hi!

 

I removed my reconnection logic and it seams to work now.

 

Thanks
